### ISSUE TITLE
Allow extending the class

### ISSUE THREAD

**Issue by mas-dude** [brunotavares/Ext.ux.Router#12]
My project is structured in modules, and I would like to load the modules on demand and I found that a nice place to do that was in the dispatch function (eg check if controller is loaded otherwise load the module on demand and continue).

My approach was to extend your Router but the patch at the bottom of the script ('Patch Ext.Application to auto-initialize Router') prevents me from doing it.

The other option is to override your implementation which I think is my option at the moment. But in the future will you allow the class to be extended?

Cheers

**Comment by brunotavares** [comment]
That's an interesting idea and I believe you can accomplish it using listeners instead of patches or overrides.

``` javascript
Ext.ux.Router.on('beforedispatch', function(token, route, params) {
    var controller = Ext.ux.Router.getController(route);

    if (!controller) {
        // find a way to load it, and after loaded just call
        // Ext.ux.Router.dispatch(token, route, params) again

        // return false to stop dispatch
        return false;
    }

    //if controler is loaded, let it run
});
```

The idea is to interrupt the dispatch function and load the controller. After loaded, you can let things run again. Do you think this could work?

**Comment by mas-dude** [comment]
Yeah that worked great! But returning false to stop the dispatcher while I fetch the script fires the routemissed event. Its not a big deal at the moment. (I guess in this scenario there is a distinction between route missed and dispatch failed)
Thanks for your help.

``` javascript

Ext.ux.Router.on({

            routemissed: function (token) {
                Ext.Msg.show({
                    title: 'Error 404',
                    msg: 'Route not found: ' + token,
                    buttons: Ext.Msg.OK,
                    icon: Ext.Msg.ERROR
                });
            },

            beforedispatch: function (token, route, params) {
                var controller = Ext.ux.Router.getController(route);

                if (!controller) {

                    var moduleUrl = // get the module url for route.controller;
                    if (!moduleUrl) {
                        return false;
                    }

                    Ext.Loader.loadScript({
                        url: moduleUrl,
                        onLoad: function () {
                            Ext.ux.Router.dispatch(token, route, params);                            
                        },
                        onError: function () {
                            //TODO:                             
                        },
                        scope: this
                    });

                    // return false to stop dispatch
                    return false;
                }
                return true;
            }
});
```

**Comment by brunotavares** [comment]
Ok, so another solution would be to patch the original dispatch fn, like the code below:

``` javascript
var originalFn = Ext.ux.Router.dispatch;

Ext.ux.Router.dispatch = function(token, route, params) {
    var controller = Ext.ux.Router.getController(route);

    if (!controller) {
        // find a way to load it, and after loaded just call
        // originalFn.apply(this, arguments);

        // return true to stop dispatch
        return true;
    }

    originalFn.apply(this, arguments);
}
```

**Comment by mas-dude** [comment]
I think I like your first solution better. For the routemissed issue I am introducing a catch all route and hooking it up to an error controller to display the message. This seems to achieve the same goal. The regex works but not 100% if it is correct.

``` javascript
...
routes: [
...
 'catch all': { regex: '(.*?)', controller: 'error',  action : 'index'}
]
```

**Comment by brunotavares** [comment]
Nice ;)
