### ISSUE TITLE
Splat

### ISSUE THREAD

**Issue by mas-dude** [brunotavares/Ext.ux.Router#13]
Is a splat an optional parameter? 

What I am trying to do is have an option parameter at the end of my route. Something like this:

'projects/:projectID/role/*roleID' : 'roles#index'

Where roleID is optional. I can solve the above with two routes like below:

'projects/:projectID/role/:roleID' : 'roles#index'
'projects/:projectID/role' : 'roles#index'

But wondering if there is a way to do it in one route without regex?

Thanks

**Comment by brunotavares** [comment]
Yes @mas-dude, you can use splat for that. I added a new test case to exemplify. Thanks for the question.
