### ISSUE TITLE
Example on how to automate view rendering in dispatch event

### ISSUE THREAD

**Issue by zam6ak** [brunotavares/Ext.ux.Router#2]
In source code of the "on dispatch" event handler there is a comment:

//TIP: you could automate rendering task here, inside dispatch event

Any examples of this?
Even small ones...

**Comment by brunotavares** [comment]
```

var viewName = 'App.view.' + 
    match.controller.toLowerCase(match.controller) + '.' +
    Ext.String.capitalize(match.action);

var view = Ext.create(viewName);

Ext.Viewport.add(view);
```

Considering that I have the route 

```
'users': 'users#list',
```

The match will be using controller Users and action list. So if I name my views in a pattern like App.view.users.List, I can use the routing match to automatically render views.

My example is very simplistic. It would be good to verify if the view class really exists (Ext.ClassManager could help), and so on...

**Comment by zam6ak** [comment]
thanks!
