### ISSUE TITLE
Controllers capitalization

### ISSUE THREAD

**Issue by revolunet** [brunotavares/Ext.ux.Router#8]
Hi Bruno,

Thanks for this awesome addon :+1: . I hope to see it integrated in the official build soon !
(and aso Ext adopting the MIT licence :smile:  )

Why do you force controllers names capitalisation ?

I know its a good practice (guidelines) to capitalize class names but sometimes when you use subfolders you may want lower case in some places.

Anyway i think its better to use what the user supplied exactly and not change it automagically ?

What do you think ?

**Comment by brunotavares** [comment]
I think I get what you're saying, but could you please provide me some details or route examples that I should use as  test case?

**Comment by revolunet** [comment]
Say i have classes named `App.tabpanel.LoginForm` and `App.tabpanel.AccountPanel` arranged in a `tabpanel` subfolder, they should declared in routing like this :

``` js
 routes: {
        '/login': 'tabpanel.LoginForm#show',
        '/account': 'tabpanel.AccountPanel#show'
    },
```

Due to the actual controllers auto-capitalization, this cannot work, as the router looks for 
`TabPanel.LoginForm`.

**Comment by brunotavares** [comment]
Got it. Rather than changing what we have currently, I can create a fallback if the route is not found on the first try. I'll be checking this next.

Thanks for the report btw!
